# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 756106d338b7e905b669587ddec11340ce63e74e2b1793a97de5a27b90add64390c5aac11c25c8c532fed030e040c7a0a14d6028e2ca361e95fd2ee90d17dc4c

test:
  secret_key_base: 8bfc06eaa13020596f60e25c382aae230d0bb1bac5e140ee89724da42de851a514947f8ed4132a48408449564ba0a184b9801f462f321b7d984b4f2b9e8f9e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
